// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7tcf7-_8RrLIidGTsWr1afMZbf6rqN88',
    appId: '1:202773745834:web:1d413f394e49cf65cb40d3',
    messagingSenderId: '202773745834',
    projectId: 'chatting-app-d6b15',
    authDomain: 'chatting-app-d6b15.firebaseapp.com',
    storageBucket: 'chatting-app-d6b15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbCArYA1TTX-stQmIey474GCYIt-OiU1M',
    appId: '1:202773745834:android:5ac354805070ec75cb40d3',
    messagingSenderId: '202773745834',
    projectId: 'chatting-app-d6b15',
    storageBucket: 'chatting-app-d6b15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr32uLmy6_tvPSZ1e6xcGLpcC1qGXIIls',
    appId: '1:202773745834:ios:1a3646bb3be40200cb40d3',
    messagingSenderId: '202773745834',
    projectId: 'chatting-app-d6b15',
    storageBucket: 'chatting-app-d6b15.firebasestorage.app',
    iosBundleId: 'com.example.chatApp8sc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr32uLmy6_tvPSZ1e6xcGLpcC1qGXIIls',
    appId: '1:202773745834:ios:1a3646bb3be40200cb40d3',
    messagingSenderId: '202773745834',
    projectId: 'chatting-app-d6b15',
    storageBucket: 'chatting-app-d6b15.firebasestorage.app',
    iosBundleId: 'com.example.chatApp8sc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7tcf7-_8RrLIidGTsWr1afMZbf6rqN88',
    appId: '1:202773745834:web:0c426af9a8ad972acb40d3',
    messagingSenderId: '202773745834',
    projectId: 'chatting-app-d6b15',
    authDomain: 'chatting-app-d6b15.firebaseapp.com',
    storageBucket: 'chatting-app-d6b15.firebasestorage.app',
  );
}
